allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true

patchedDependencies:
  '@bacons/apple-targets@4.0.7': patches/apple-targets-notification-service-info-plist.patch
  '@react-native-firebase/app@25.1.0': patches/react-native-firebase-app-remove-ios-script-input.patch
